### PR TITLE
Add changes attribute

### PR DESCRIPTION
**Pull request by Gummibeer**
**solves** #264 

I've improved the original `changes()` method and made it a bit more readable and added the `changes` attribute.

### CODE REVIEW

**Comment by freekmurze** [comment]
On first sight, this looks like an awesome PR. I'll review it in full soon!

**Comment by freekmurze** [comment]
Thanks

**Comment by Gummibeer** [comment]
Should I edit the documentation in any way or will you do it while you create the new v3 docs?

**Comment by freekmurze** [comment]
I've already created the v3 docs with the necessary changes. They are available here: https://docs.spatie.be/laravel-activitylog/v3/introduction

If you spot an error or something that can be improved feel free to send a PR by clicking on the `edit` button of a page.

Thanks for all your work in the recent PRs. Much appreciated! 👍

**Pull request merged**
