### PR TITLE
User can change auth driver.

### PR DESCRIPTION
**Pull request by aguimaraes**
My attempt to close the issue #23 based on [this comment](https://github.com/spatie/laravel-activitylog/issues/23#issuecomment-232928719)

### CODE REVIEW

**Comment by freekmurze** [comment]
Looking good for Laravel 5.2, but does the `web` driver you set as a default exist in L5.1?

**Comment by aguimaraes** [comment]
Do you think it's better to get the default guard set on config/auth.php?

**Comment by aguimaraes** [comment]
@freekmurze ping

**Comment by freekmurze** [comment]
Looks good!

**Comment by freekmurze** [comment]
These changes are present in the newly tagged version `1.3.0` 

Thank you very much for work!

**Pull request merged**
