### PR TITLE
Do not tap activities twice

### PR DESCRIPTION
**Pull request by jrmajor**
Fixes a bug introduced in #1031.

### CODE REVIEW

**Review by Gummibeer — CHANGES_REQUESTED** [review]
That's not a fix - it removes a feature.

**Comment by jrmajor** [comment]
@Gummibeer What feature is being removed? Is it a feature that the `tapActivity()` method gets called twice?

**Comment by jrmajor** [comment]
```php
// tapActivity() is called from LogsActivity (these are the lines I've removed)
if (method_exists($model, 'tapActivity')) {
    $logger->tap([$model, 'tapActivity'], $eventName);
}

// #1031 added a tapActivty() call in this method, so without
// the previous lines being removed, it will be called twice
$logger->log($description);
```

**Comment by krembo** [comment]
The solution is good as `tapActivity` is called in `log()` method anyway.

**Comment by chWagnr** [comment]
@Gummibeer Is it possible to reopen the request?

`tapActivity` is definitly called twice

**Comment by jrmajor** [comment]
They fixed it after all in #1441.

**Pull request closed without merging**
