### PR TITLE
enable/disable global logging

### PR DESCRIPTION
**Pull request by DemianD**
**Issue:** #401 

This PR will make it possible to disable/enable logging globally. Therefore, I've made the `ActivityLogger` a singleton.

- [x] Tests

### CODE REVIEW

**Comment by freekmurze** [comment]
Looks good 👍 

Could you also send a PR to the docs? There's an edit button on every page: https://docs.spatie.be/laravel-activitylog/v2/introduction

**Comment by DemianD** [comment]
Hi @freekmurze , I've created a PR: https://github.com/spatie/docs.spatie.be/pull/331

**Comment by freekmurze** [comment]
Thanks!

**Comment by Quix0r** [comment]
For those stuck with older Laravel (5.3 here) versions, you don't have `disableLogging()` method. You may want to use the following code instead:

````
Config::set('laravel-activitylog.enabled', false);
````

**Comment by vahidalvandi** [comment]
i use this but not disable

 ```
           $new_offline_payment = offline_payment::create([
                'wallet_id' => $wallet_id,
                'amount' => $request->amount,
                'currency' => $currency,
                'note' => $request->note,
                'is_apply' => 0,
            ]);

            $new_offline_payment->disableLogging();

```

**Comment by vahidalvandi** [comment]
> Looking fine?

cant find ~

**Pull request merged**
