### PR TITLE
Support softdeleted models

### PR DESCRIPTION
**Pull request by wpouseele**
As requested, new pull request for #29

### CODE REVIEW

**Comment by freekmurze** [comment]
Hi thanks for creating this so quick.

However the tests still seem to fail. Could you check that?

**Comment by wpouseele** [comment]
Need a little help here, the test works fine on my environment. 
This error pops up, when the subject_withTrashed is set to false in the config file (default value), but the test [sets this value to true](https://github.com/spatie/laravel-activitylog/pull/33/commits/67dbfc1772b7b7defde96391713ed8449aa09ecf#diff-b2934a55a0e11b0db1a66abdb3dd1e7aR82).

**Comment by freekmurze** [comment]
The test are ok with the latest version of the dependencies, but when using the lower version of the dependencies it fails. 

You can simulate those low dependencies by running `composer update --prefer-lowest`. More info [here](https://evertpot.com/testing-composer-prefer-lowest/).

With those lower dependencies installed, the test on your machine should fail too and you can starting debugging and finding a fix.

**Comment by freekmurze** [comment]
At this time I'm not willing to drop L5.1 compatiblity just yet. Can you find a way to make the tests pass without requiring a L5.2 component?

**Comment by freekmurze** [comment]
Meanwhile we've dropped L5.1 compatiliby, so rely on L5.2 is now possible. However there are some merge conflicts. Could you please rebase against the current master?

**Comment by wpouseele** [comment]
Will open new PR, containing all changes.

**Pull request closed without merging**
