### PR TITLE
V4

### PR DESCRIPTION
**Pull request by Gummibeer**
* [x] drop Laravel 6 support **?**
* [x] drop PHP 7.2 and 7.3 support **?**
* [x] new column for event type #673 #702 
* [x] activity batches #560 
* [x] define causer for runtime #661 #649 #582 #503 
* [x] deep diff array/JSON sub-keys and respect for only-dirty, no-empty ... #692 
* [x] add `withProperties()`, `withCauser()` methods #700 
* [x] move logged attributes into old key for deleted event #760 #767  
* [x] #730

### CODE REVIEW

**Comment by nagi1** [comment]
That's weird I have tested it on windows and all green!

**Comment by nagi1** [comment]
Readme needs to be updated. if you suggest something let me know.

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-activitylog/releases/tag/4.0.0

**Comment by emielmolenaar** [comment]
Thanks guys!

**Pull request merged**
