### PR TITLE
Make it possible to use Laravel 5.5

### PR DESCRIPTION
**Pull request by LKDevelopment**

### CODE REVIEW

**Comment by m1guelpf** [comment]
See https://github.com/spatie/laravel-activitylog/pull/223

**Comment by LKDevelopment** [comment]
Sure, but actually the composer lines are the only error on using this package at 5.5. If it's okay for @freekmurze i will check all Laravel Packages from spatie tomorrow if there are compatible with laravel 5.5 and if not i make them compatible. So Freeks GMail Inbox could be a little bit cleaner :)

**Comment by m1guelpf** [comment]
@LKDevelopment That'd be awesome!

**Comment by freekmurze** [comment]
@LKDevelopment Thanks, I'll start adding L5.5 dev branches soon to our big packages and the ones where you report compatibility problems.

General guideline: I'd like to use as much L5.5 specific features as possibles, and I'm willing to drop support for older Laravel versions in all packages.

**Comment by LKDevelopment** [comment]
@freekmurze i've developed something that make it a little bit easier to upgrade packages. It's a little bit like laravel shift.  (See #231)  I would start the tool for all your Laravel Tools if it is okay :)

**Comment by freekmurze** [comment]
This will be handled in #231

**Pull request closed without merging**
