### PR TITLE
feat!: add laravel 11 support

### PR DESCRIPTION
**Pull request by StevePorter92**
This PR adds PHP 8.3 and Laravel 11 to testing matrix and updates illuminate dependencies.

BREAKING CHANGE: Drops support for PHP 8.0 and Laravel 8

### CODE REVIEW

**Comment by gabrielrbarbosa** [comment]
+1

**Comment by gabrielrbarbosa** [comment]
@Gummibeer

**Comment by Gummibeer** [comment]
@gabrielrbarbosa

**Comment by Gummibeer** [comment]
Sorry Gabriel, but PRs are handled when they are handled. Instead of reviewing the PR I now have to spend my time with this comment to educate you how to behave. Yes, this PR is open since 12d which was exactly the day after Laracon EU - probably even the reason for the PR. 🤷‍♂️
After that I had to get back to my wife and baby and get some work done to buy more diapers.

Yes, you want to test L11, be prepared and are enthusiastic - I get that. But that's open source, we are all doing it in our free time, we all have a real life and real jobs and I'm also not the only maintainer.

Ideas for the future, instead of just tagging someone or commenting 2 characters.
* Be patient and wait, when have the urgent feeling to comment you should value all others time and not just tag someone but provide feedback or offer help.
* You can do a real code review to request improvements or guarantee with your name that it's good as is.
* You can checkout the code/require the feature branch in your local project to test it with production code for any possible BCs or other issues.

**Comment by tpetry** [comment]
Why was the minimum PHP version increased? I don't see the need for that BC change.

**Comment by gabrielrbarbosa** [comment]
@Gummibeer sorry for the pings I get it if you want to wait full stable release before merging this PR.
I've tested Laravel Shift PR for L11 (#1280) and it works fine here, if you guys prefer to keep current php versions to 8.0 and merge that PR thats your call.

Only edge case I could find (not sure if is a breaking change) is if someone change db driver to mariadb, because "batch_uuid" would be already created with char(36) and now it will use native uuid type as merged here:
https://github.com/laravel/framework/pull/50192

**Pull request merged**
