### PR TITLE
Handle null value for `causedBy`

### PR DESCRIPTION
**Pull request by EmilMoe**
This is useful when you have conditional statements for the value.

For example:

```
->causedBy(Auth::check() ? Auth::user() : null)
```

### CODE REVIEW

**Comment by EmilMoe** [comment]
I fixed the error from `continuous-integration/styleci/pr — Issues have been identified with 1 file` but seems like it's not re-scanning.

**Comment by EmilMoe** [comment]
Travis error seems to be related to some other parts of the codebase.

**Comment by freekmurze** [comment]
Could you add a test that provided that `causedBy` now works when passing `null`?

**Comment by Gummibeer** [comment]
@EmilMoe your change isn't precise enough - it accepts everything that's converted to `false`. Primary the `0` could lead to problems if I use custom IDs for my Model.
http://sandbox.onlinephpfunctions.com/code/54f28c289472fd661af7d39dc68e457d140c5b91

A more precise solution would be:
```php
if (is_null($modelOrId)) {
  return;
}
```

And it work's but isn't nice - the test would be better in the same PR (here) and not another one. But this is just beauty.^^

**Comment by EmilMoe** [comment]
@Gummibeer how about `$modelOrId === null`. That should work too afaik?

**Comment by EmilMoe** [comment]
Thanks @Gummibeer I have modified my PR

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
