### PR TITLE
Added optional days argument to clean command

### PR DESCRIPTION
**Pull request by bradcis**
Please bear with me, @freekmurze and team! This is my first ever pull request, so I'm hoping I'm following the proper procedure.

I'm requesting we add the ability to set the number of days threshold on the activitylog:clean command if the end user wants to deviate from the default set in the config file. The use case is that you may have multiple logs and want the retention period to be different for each one of them (i.e. user activities are deleted after 7 days where as project activities are deleted after 30 days). 

The end user could then add the activitylog:clean command to their schedule with each variation.

### CODE REVIEW

**Comment by Gummibeer** [comment]
I like this idea! The only thing is that I would use it as an option and not as argument. Arguments have to be in a fixed order and with every new it get's more complex. That's why I like to have commands with just one argument and the others - primary if optional - as option.
Except of this the PR is fine and I would like to merge it.

**Comment by freekmurze** [comment]
Thank you for this PR. Like @Gummibeer suggested, an option would be better in this case. Could you also add a test to ensure that it works as intended.

**Comment by bradcis** [comment]
Thank you guys! I've updated the code to use an option rather than argument and added test coverage. Will this work?

**Comment by Gummibeer** [comment]
@bradcis and could you please merge the current master in here - this will let pass all unittests again. :)

**Comment by Gummibeer** [comment]
I've merged it into `spatie:ft-command-days-option` to update my requests and prepare it for a release. Thanks @bradcis for your work here!

**Comment by bradcis** [comment]
Thanks for finishing this up, @Gummibeer! I apologize for not responding sooner.

**Pull request merged**
