### PR TITLE
Log only dirty fields

### PR DESCRIPTION
**Pull request by LasseRafn**
I made it so that model classes can have an attribute. `$onlyDirty` that defines if it should only log changes. The structure is the same, and it defaults to `false`

I made two tests related to this, and all previous tests still pass of cause.

Will probably need some polishing.
-------
Related: issue #57

### CODE REVIEW

**Comment by LasseRafn** [comment]
I tried with `$model->getDirty()`, but it would require a tad more code, so this seems to be a decent solution I guess.

**Comment by LasseRafn** [comment]
Okay, StyleCI is a pain right now.. Guess it can be fixed with their PR function if this is merged 👍

**Comment by LasseRafn** [comment]
I renamed the variable from `$onlyDirty` to `$logDirtyOnly` — To match the style of the other variables + so it makes more sense 👍 .

**Comment by freekmurze** [comment]
Thank you very much, I'll take care of some nitpicks myself

Could you also create a PR that adds some documentation for this feature at https://docs.spatie.be/laravel-activitylog/?

**Comment by LasseRafn** [comment]
No problem — Sure, will do! 👍

**Pull request merged**
