### PR TITLE
Add support for Laravel 5.1

### PR DESCRIPTION
**Pull request by JeroenNoten**
In answer to this issue: https://github.com/spatie/laravel-activitylog/issues/7, I added support for Laravel 5.1.

Do you also want to support PHP 5.6? Since Laravel 5.1 runs on PHP 5.6...

### CODE REVIEW

**Comment by freekmurze** [comment]
Awesome thanks! Did you run the unit test locally too prove that it works? (there are a few tests that do not run on Travis (yet))

**Comment by freekmurze** [comment]
And to answer your other question: we'll leave the required PHP version at 7.0

**Comment by JeroenNoten** [comment]
Yes, I ran phpunit after 'composer update --prefer-lowest-version' as well as after 'composer update' and all tests succeeded in both ways.

**Comment by freekmurze** [comment]
Nice! I'll fix some nitpicks and tag a new version. Thanks again for this awesome contribution.

**Pull request merged**
