### PR TITLE
Added support to configure database connection.

### PR DESCRIPTION
**Pull request by imrealashu**
Very handy to log all activities for the application having multiple database connections.

### CODE REVIEW

**Comment by Sarnodeep** [comment]
👍

**Comment by freekmurze** [comment]
Is it possible to accomplish this by using a custom model and specify the connection in it's static `boot`method?

**Comment by imrealashu** [comment]
yeah, setting connection using `setConnection()` method in the constructor, using custom model is working fine. 
```php
public function __construct()
    {
        parent::setConnection('connection_name');
    }
```

But this feature which I've suggested is quite handy as well and easy to configure. any thoughts @freekmurze ?

**Comment by freekmurze** [comment]
Gonna hold of on this for now, as this behaviour is also easily implemented using a custom model.

**Pull request closed without merging**
