### PR TITLE
Update ActivityloggerTest.php

### PR DESCRIPTION
**Pull request by EmilMoe**

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you add this to #367 ?

**Comment by EmilMoe** [comment]
@freekmurze I must admit I was a bit lost on how to do it. Do you have a hint or link?

**Comment by Gummibeer** [comment]
You've edited in the browser - this is ok for simple changes but hard to keep the branches.
You have to checkout this branch https://github.com/EmilMoe/laravel-activitylog/tree/patch-1 and edit the file.
It could be that you also can edit the file in the browser if you use the given link.

related help article: https://help.github.com/articles/fork-a-repo/

**Comment by Gummibeer** [comment]
@EmilMoe if you need an IDE that supports you with all these nice things like: autocomplete, git support, syntax highlighting and so on: https://atom.io (it's the "best" free one I know) or if you have some money use PhpStorm.

**Pull request closed without merging**
