### PR TITLE
Using the nullableMorphs() method

### PR DESCRIPTION
**Pull request by arcanedev-maroc**
Closes: #454

### CODE REVIEW

**Comment by Gummibeer** [comment]
@arcanedev-maroc thanks for your PR.
So far I got it in the [docs](https://laravel.com/docs/5.5/migrations#columns) this just replaces the 4 lines but doesn't add indexes, like requested in #454 .
Or does it add indexes but this isn't written in the docs? 

In general I like this change which reduces the amount of lines without any real changes. 👍 I'm just unsure if it really closes the linked PR!?

**Comment by arcanedev-maroc** [comment]
This is what `nullableMorphs()` does

https://github.com/laravel/framework/blob/b18c2535fcdaa69d83309ac4524a9a6b1a6850f2/src/Illuminate/Database/Schema/Blueprint.php#L1174-L1188

**Comment by Gummibeer** [comment]
Ok, if it adds the indexes I have the same concerns I described in #454 . 🤔

**Comment by arcanedev-maroc** [comment]
How about using the **Custom Polymorphic Types** ??

You can found the section in the [documentation about the polymorphic relations](https://laravel.com/docs/5.5/eloquent-relationships#polymorphic-relations)

**Comment by Gummibeer** [comment]
This would be an idea for the app developer. But I don't see a way how we could introduce this via this package. The next problem is that this map is a app wide one. So one model has only one mapping for all polymorphic relations.

I really don't see a way to add indexes, in this package, without the disadvantages. And because of the simplicity to let the developer add the indexes I wouldn't add them to this package.
I really appreciate the work done by you and others for this and like said would let @freekmurze do the final decision - but for me string indexes on a log table have more disadvantages than benefits. 😣

**Comment by freekmurze** [comment]
I agree with @Gummibeer, if the user needs indexes he/she can add them manually in their app.

Thanks for your work, but as for now, we're going to pass.

**Pull request closed without merging**
