### PR TITLE
Fix db migration for spatie/laravel-package-tools

### PR DESCRIPTION
**Pull request by mallardduck**
Per:

https://github.com/spatie/laravel-package-tools/blob/4bb554dc9870127606c34d906a602989b8b376ff/src/PackageServiceProvider.php#L62

Based on these errors:
```bash
Can't locate path: </Users/danpock/sites/laravel/vendor/spatie/laravel-activitylog/src/../database/migrations/CreateActivityLogTable.php.stub>
Can't locate path: </Users/danpock/sites/laravel/vendor/spatie/laravel-activitylog/src/../database/migrations/AddEventColumnToActivityLogTable.php.stub>
Can't locate path: </Users/danpock/sites/laravel/vendor/spatie/laravel-activitylog/src/../database/migrations/AddBatchUuidColumnToActivityLogTable.php.stub>
```

### CODE REVIEW

**Comment by mallardduck** [comment]
@Gummibeer - Found while helping on docs stuff.

**Comment by mallardduck** [comment]
Just as an aside - I think the package-tools repo needs a fix too.
Doing a quick little hack to make it work in the "wrong" spot, I found it moved the files to odd names:
```bash
Copied File [/vendor/spatie/laravel-activitylog/migrations/CreateActivityLogTable.php.stub] To [/database/migrations/2021_04_26_011035_CreateActivityLogTable.php]
Copied File [/vendor/spatie/laravel-activitylog/migrations/AddEventColumnToActivityLogTable.php.stub] To [/database/migrations/2021_04_26_011036_AddEventColumnToActivityLogTable.php]
Copied File [/vendor/spatie/laravel-activitylog/migrations/AddBatchUuidColumnToActivityLogTable.php.stub] To [/database/migrations/2021_04_26_011037_AddBatchUuidColumnToActivityLogTable.php]
Publishing complete.
```

So I'm thinking that package needs to `Str::of($migrationFileName)->snake()->finish('.php')`

**Comment by Gummibeer** [comment]
@freekmurze could you please take a look if that's the right change or if the package tools are intended to be used differently? 🤔

**Comment by mallardduck** [comment]
Now that https://github.com/spatie/laravel-package-tools/pull/28 is merged after this is accepted things should work as expected.

**Comment by Gummibeer** [comment]
Could you bump the minimum version of package tools to `1.6.3` - after that I will merge this PR in.

**Comment by mallardduck** [comment]
@Gummibeer - can do, I had that thought too.

Wasn't sure about doing it since TBH composer rules trip me up some times.
IIRC `^1.6.3` will keep it on `1.6.x` where as the current rule keeps it on `1.x`
And I didn't know if that would be considered an issue or concern or not.

**Comment by Gummibeer** [comment]
`^1.6.3` is fine - only `~1.6.3` would prevent a `1.7.0` update.

https://getcomposer.org/doc/articles/versions.md#caret-version-range-

**Review by Gummibeer — APPROVED** [review]

**Comment by Gummibeer** [comment]
Thanks for this fix Dan! 🎉

**Review by Gummibeer — CHANGES_REQUESTED** [review]
Oh, since you've renamed the migrations the tests are failing now - can you fix this as well?

**Comment by mallardduck** [comment]
Ope - my fault! Absolutely can get that fixed now.

**Comment by mallardduck** [comment]
@Gummibeer - the tests are fixed locally, looks like actions need to be approved before the run to verify on GH.

**Pull request merged**
