### PR TITLE
Add doc blocks generated by IDE helper

### PR DESCRIPTION
**Pull request by gauravmak**
As per https://github.com/spatie/laravel-activitylog/discussions/950

Closes https://github.com/spatie/laravel-activitylog/issues/951

### CODE REVIEW

**Comment by gauravmak** [comment]
@Gummibeer Nothing to pressure but I am not sure if you were notified about this so just pinging.

**Comment by humaneguy** [comment]
Have you run Larastan test on this and it fixes @Gummibeer issue?

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-activitylog/releases/tag/4.4.1

**Comment by gauravmak** [comment]
Thanks for pointing it out @fabio-ivona. Just added a [PR](https://github.com/spatie/laravel-activitylog/pull/1018) with the fix

**Pull request merged**
