### PR TITLE
Added optional days argument to clean command

### PR DESCRIPTION
**Pull request by Gummibeer**
**based on:** #484 
**docs:** https://github.com/spatie/docs.spatie.be/pull/392

### CODE REVIEW

**Comment by freekmurze** [comment]
There is a test failing. Seems unrelated to this PR though.

**Comment by Gummibeer** [comment]
@freekmurze it's fixed by #498

**Comment by Gummibeer** [comment]
@freekmurze could you release this? The changelog doesn't match with the real releases. So I don't know which one is right.

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-activitylog/releases/tag/3.5.0

**Pull request merged**
