### PR TITLE
Add a subjects trait

### PR DESCRIPTION
**Pull request by eduardokum**
Adds the ability to include this trait in model to show activities for this subject.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks for contributing.

I'm not going to merge as the package already contains a `CausesActivity` trait that does the same.

**Comment by eduardokum** [comment]
Sorry I thought `CausesActivity` only get user related and not the model changed.

**Comment by freekmurze** [comment]
v1.1.0 of the package introduces an `activity` method in the `LogsActivity`-trait that 'll return all activities performed on the subject.

**Comment by eduardokum** [comment]
Thanks man

**Pull request closed without merging**
